spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shop
    #    username: postgres
    #    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/togumetest
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false