version: '3'
services:

  end:
    image: enderwar/togumesecurity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5113

    ports:
      - 5113:5113   
