version: '3'
services:
  suraifokkusu-message-service:
    image: suraifokkusu/chat-message-service:v.1.0
    ports:
      - 8080:8080
#    depends_on:
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/entrypoint.sh"

#  db:
    #    image: postgres
    #    restart: always
    #    environment:
    #      POSTGRES_PASSWORD: password
    #    ports:
    #    - 5432:5432

  apatrios-db-init:
    image: apatrios/db-control-module:latest
    ports:
      - 8189:8189
    depends_on:
      - db
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/entrypoint.sh"
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: